# Generated by Django 5.2.4 on 2025-08-27 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_name', models.CharField(max_length=200)),
                ('municipal_code', models.CharField(blank=True, max_length=50)),
                ('municipal_type', models.CharField(blank=True, max_length=50)),
                ('county_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('gnis_id', models.CharField(blank=True, max_length=20)),
                ('fips_code', models.CharField(blank=True, max_length=20)),
                ('fips_name', models.CharField(blank=True, max_length=100)),
                ('pop_1990', models.IntegerField(null=True)),
                ('pop_2000', models.IntegerField(null=True)),
                ('pop_2010', models.IntegerField(null=True)),
                ('pop_2020', models.IntegerField(null=True)),
                ('sq_mi', models.FloatField(null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'municipal_boundaries',
                'managed': False,
            },
        ),
    ]
