# Generated by Django 5.2.4 on 2025-08-28 12:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateBoundary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('statefp', models.TextField(null=True)),
                ('statens', models.TextField(null=True)),
                ('geoidfq', models.TextField(null=True)),
                ('geoid', models.TextField(null=True)),
                ('stusps', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('lsad', models.TextField(null=True)),
                ('aland', models.BigIntegerField(null=True)),
                ('awater', models.BigIntegerField(null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4269)),
            ],
            options={
                'db_table': 'state_boundaries',
                'managed': False,
            },
        ),
    ]
