# Generated by Django 5.2.4 on 2026-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_viewer', '0003_municipalboundaries_municipalfinances_municipalities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingData',
            fields=[
                ('gap_id', models.UUIDField(primary_key=True, serialize=False)),
                ('municipality_id', models.UUIDField()),
                ('year', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('data_point', models.CharField(max_length=200)),
                ('section_name', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('pdf_page_indices', models.TextField(blank=True, null=True)),
                ('markdown_context', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'missing_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFinanceUpdatesLog',
            fields=[
                ('update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('mid', models.UUIDField()),
                ('year', models.IntegerField()),
                ('field_name', models.CharField(max_length=200)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('modification_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_finances_updates_log',
                'managed': True,
            },
        ),
    ]
